namespace: ansible
name: ovs
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ansible.ovs.git
documentation: https://github.com/ansible-collection-migration/ansible.ovs/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.ovs
issues: https://github.com/ansible-collection-migration/ansible.ovs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
